package crimeMap.model;

public class OffenseType {
  protected int reportId;
  protected Type offenseType;
  
  public enum Type {
	  DRUG_NARCOTIC_VIOLATIONS,
	  THEFT_OF_MOTOR_VEHICLE_PARTS_OR_ACCESSORIES,
	  ROBBERY,
	  DESTRUCTION_DAMAGE_VANDALISM_OF_PROPERTY,
	  DRIVING_UNDER_THE_INFLUENCE,
	  SHOPLIFTING,
	  THEFT_FROM_MOTOR_VEHICLE,
	  WIRE_FRAUD,
	  COUNTERFEITING_FORGERY,
	  ALL_OTHER_LARCENY,
	  PORNOGRAPHY_OBSCENE_MATERIAL,
	  EXTORTION_BLACKMAIL,
	  MOTOR_VEHICLE_THEFT,
	  THEFT_FROM_BUILDING,
	  STOLEN_PROPERTY_OFFENSES,
	  FALSE_PRETENSES_SWINDLE_CONFIDENCE_GAME,
	  CREDIT_CARD_AUTOMATED_TELLER_MACHINE_FRAUD,
	  EMBEZZLEMENT,
	  IDENTITY_THEFT,
	  IMPERSONATION,
	  WEAPON_LAW_VIOLATIONS,
	  HACKING_COMPUTER_INVASION,
	  DRUG_EQUIPMENT_VIOLATIONS,
	  ARSON,
	  LIQUOR_LAW_VIOLATIONS,
	  BAD_CHECKS,
	  POCKET_PICKING,
	  PURCHASING_PROSTITUTION,
	  PURSE_SNATCHING,
	  THEFT_FROM_COIN_OPERATED_MACHINE_OR_DEVICE,
	  CURFEW_LOITERING_VAGRANCY_VIOLATIONS,
	  ANIMAL_CRUELTY,
	  PROSTITUTION,
	  WELFARE_FRAUD,
	  ASSISTING_OR_PROMOTING_PROSTITUTION,
	  DRUNKENNESS,
	  BRIBERY,
	  OPERATING_PROMOTING_ASSISTING_GAMBLING,
	  BETTING_WAGERING,
	  GAMBLING_EQUIPMENT_VIOLATION,
	  TRESPASS_OF_REAL_PROPERTY,
	  SIMPLE_ASSAULT,
	  AGGRAVATED_ASSAULT,
	  INTIMIDATION,
	  BURGLARY_BREAKING_ENTERING
  }

  public int getReportId() {
    return reportId;
  }

  public void setReportId(int reportId) {
    this.reportId = reportId;
  }

  public Type getOffenseType() {
    return offenseType;
  }

  public void setOffenseType(Type offenseType) {
    this.offenseType = offenseType;
  }
}
