package crimeMap.model;

public class RegionCategory {
  protected int reportId;
  protected Region region;
  
  public enum Region {
    ALASKA_JUNCTION, ALKI, BALLARD_NORTH, BALLARD_SOUTH, BELLTOWN, BITTERLAKE, BRIGHTON_DUNLAP, 
    CAPITOL_HILL,CENTRAL_AREA_SQUIRE_PARK,CHINATOWN_INTERNATIONAL_DISCTRICT,CLAREMONT_RANIER_VISTA,
    COLUMBIA_CITY,COMMERCIAL_DUWAMISH, COMMERCIAL_HARBOR_ISLAND,DOWNTOWN_COMMERCIAL,EASTLAKE_EAST,
    EASTLAKE_WEST,FAUNTLEROY_SW, FIRST_HILL,FREMONT, GENESEE, GEORGETOWN,GREENWOOD, HIGH_POINT,
    HIGHLAND_PARK, HILLMAN_CITY_JUDKINS_PARK_NORTH_BEACON_H,LAKECITY, LAKEWOOD_SEWARD_PARK,
    MADISON_PARK, MADRONAL_LESCHI,MAGNOLIA, MID_BEACON_HILL,MILLER_PARK,MONTLAKE_PORTAGE_BAY, MORGAN,
    MOUNT_BAKER, NEW_HOLLY, NORTH_ADMIRAL, NORTH_BEACON_HILL, NORTH_DELRIDGE, NORTHGATE,
    PHINNY_RIDGE, PIGEON_POINT, PIONEER_SQUARE, QUEEN_ANNE, RANIER_BEACH, RANIER_VIEW
  }

  public int getReportId() {
    return reportId;
  }

  public void setReportId(int reportId) {
    this.reportId = reportId;
  }

  public Region getRegion() {
    return region;
  }

  public void setRegion(Region region) {
    this.region = region;
  }
}
